PKG_ID := $(shell yq -e ".id" manifest.yaml)
PKG_VERSION := $(shell yq -e ".version" manifest.yaml)
BUILD_DIR := builds/$(PKG_VERSION)
TS_FILES := $(shell find . -name \*.ts -not -path './startos/*' -not -path './node_modules/*' )
# All backend/frontend sources baked into the image. Listed explicitly so `make`
# rebuilds when any of them change (the Dockerfile ADDs the whole dirs, but make
# only re-runs when a named prerequisite is newer).
APP_FILES := $(shell find app/backend app/frontend -type f)

.DELETE_ON_ERROR:

all: verify

verify: $(PKG_ID).s9pk
	@start-sdk verify s9pk $(PKG_ID).s9pk
	@echo " Done!"
	@echo "   Filesize: $(shell du -h $(PKG_ID).s9pk) is ready"

install:
	@if [ ! -f ~/.embassy/config.yaml ]; then echo "You must define \"host: http://server-name.local\" in ~/.embassy/config.yaml config file first."; exit 1; fi
	@echo "\nInstalling to $$(grep -v '^#' ~/.embassy/config.yaml | cut -d'/' -f3) ...\n"
	@[ -f $(PKG_ID).s9pk ] || ( $(MAKE) && echo "\nInstalling to $$(grep -v '^#' ~/.embassy/config.yaml | cut -d'/' -f3) ...\n" )
	@start-cli package install $(PKG_ID).s9pk

release: verify
	rm -rf $(BUILD_DIR)
	mkdir -p $(BUILD_DIR)
	cp $(PKG_ID).s9pk $(BUILD_DIR)/
	cd $(BUILD_DIR) && sha256sum hashgg.s9pk > SHA256SUMS

clean:
	rm -rf docker-images
	rm -f $(PKG_ID).s9pk
	rm -f scripts/*.js

scripts/embassy.js: $(TS_FILES)
	deno run --allow-read --allow-write --allow-net --allow-env scripts/bundle.ts

arm:
	@rm -f docker-images/x86_64.tar
	ARCH=aarch64 $(MAKE)

x86:
	@rm -f docker-images/aarch64.tar
	ARCH=x86_64 $(MAKE)

# `manifest.yaml` is a prerequisite because `--tag` below embeds `$(PKG_VERSION)`,
# which is read from it. Without it a version-only bump leaves these tarballs
# looking up to date, and the pack fails with "Contains image with incorrect
# version: expected 0.7.2.1 received 0.7.2.0", which reads as a packaging fault
# rather than a stale build product.
docker-images/aarch64.tar: Dockerfile docker_entrypoint.sh check-tunnel.sh check-datum.sh $(APP_FILES) icon.png instructions.md manifest.yaml
ifeq ($(ARCH),x86_64)
else
	mkdir -p docker-images
	docker buildx build --tag start9/$(PKG_ID)/main:$(PKG_VERSION) --build-arg ARCH=aarch64 --build-arg PLATFORM=arm64 --build-arg HASHGG_PLATFORM=startos-0.3 --platform=linux/arm64 -o type=docker,dest=docker-images/aarch64.tar .
endif

docker-images/x86_64.tar: Dockerfile docker_entrypoint.sh check-tunnel.sh check-datum.sh $(APP_FILES) icon.png instructions.md manifest.yaml
ifeq ($(ARCH),aarch64)
else
	mkdir -p docker-images
	docker buildx build --tag start9/$(PKG_ID)/main:$(PKG_VERSION) --build-arg ARCH=x86_64 --build-arg PLATFORM=amd64 --build-arg HASHGG_PLATFORM=startos-0.3 --platform=linux/amd64 -o type=docker,dest=docker-images/x86_64.tar .
endif

$(PKG_ID).s9pk: manifest.yaml instructions.md icon.png LICENSE scripts/embassy.js docker-images/aarch64.tar docker-images/x86_64.tar
ifeq ($(ARCH),aarch64)
	@echo "start-sdk: Preparing aarch64 package ..."
else ifeq ($(ARCH),x86_64)
	@echo "start-sdk: Preparing x86_64 package ..."
else
	@echo "start-sdk: Preparing Universal Package ..."
endif
	@start-sdk pack

# === StartOS 0.4.0 targets ===
.PHONY: pack-040 pack-040-x86 pack-040-arm install-040 clean-040 release-all

pack-040: pack-040-x86 pack-040-arm

pack-040-x86: javascript/index.js
	start-cli s9pk pack --arch=x86_64 -o $(PKG_ID)_x86_64.s9pk

pack-040-arm: javascript/index.js
	start-cli s9pk pack --arch=aarch64 -o $(PKG_ID)_aarch64.s9pk

# The variant is baked into the bundle rather than read from the environment,
# because startos/ is evaluated twice: once by `start-cli s9pk pack`, which has an
# environment, and again on the StartOS host when the service starts, which does
# not. Written before every build so the bundle and the manifest cannot disagree.
VARIANT ?= flagship

# Always evaluated, but only rewritten when the value actually changes, so the
# bundle rebuilds when you switch variants and not otherwise. A plain
# `: Makefile` prerequisite is wrong here: switching VARIANT does not touch the
# Makefile, so the stale file survives and the next build silently packs the
# previous variant's identity.
.PHONY: FORCE
FORCE:

startos/variant.build.ts: FORCE
	@printf '%s\n' \
	  '/** GENERATED by the Makefile. Do not edit, do not commit. See startos/variant.ts. */' \
	  'export const BUILD_VARIANT: string = '"'"'$(VARIANT)'"'"'' > $@.tmp
	@cmp -s $@.tmp $@ 2>/dev/null && rm -f $@.tmp || mv $@.tmp $@

javascript/index.js: $(shell find startos -type f -not -name variant.build.ts 2>/dev/null) tsconfig.json node_modules startos/variant.build.ts
	npm run build

node_modules: package-lock.json
	npm ci

package-lock.json: package.json
	npm i

install-040: pack-040-x86
	@HOST=$$(awk -F'/' '/^host:/ {print $$3}' ~/.startos/config.yaml); \
	if [ -z "$$HOST" ]; then echo "Error: Define \"host: http://server-name.local\" in ~/.startos/config.yaml"; exit 1; fi; \
	printf "\nInstalling to $$HOST ...\n"; \
	start-cli package install -s $(PKG_ID)_x86_64.s9pk

# Build both 0.3.5.1 and 0.4.0 universal packages into builds/<version>/
release-all: verify javascript/index.js
	rm -rf $(BUILD_DIR)
	mkdir -p $(BUILD_DIR)
	cp $(PKG_ID).s9pk $(BUILD_DIR)/hashgg-0351.s9pk
	start-cli s9pk pack -o $(BUILD_DIR)/hashgg-040.s9pk
	cd $(BUILD_DIR) && sha256sum *.s9pk > SHA256SUMS
	@echo ""
	@echo "Release builds:"
	@ls -lh $(BUILD_DIR)/
	@echo ""
	@cat $(BUILD_DIR)/SHA256SUMS

# The companion package: same sources, same image, different manifest and icon.
# Forces a rebuild of the generated variant and the bundle, because the previous
# target left them set to whatever it built.
companion-040:
	$(MAKE) VARIANT=companion javascript/index.js
	HASHGG_VARIANT=companion start-cli s9pk pack \
	  -o $(BUILD_DIR)/hashgg-companion-040.s9pk \
	  --icon icon-companion.png
	@echo "  built $(BUILD_DIR)/hashgg-companion-040.s9pk"

clean-040:
	rm -f $(PKG_ID)_x86_64.s9pk $(PKG_ID)_aarch64.s9pk
	rm -rf javascript node_modules

clean-all: clean clean-040

# === Generic Docker image (Docker Hub) ===
# Used for the plain-Docker deployment path (Linux host running Datum Gateway
# natively, HashGG in a container). Not used by StartOS.
#
# Override with `make docker-build-local DOCKER_TAG=0.4.0.0` etc.
DOCKER_REPO ?= paulscode/hashgg
DOCKER_TAG  ?= $(PKG_VERSION)

.PHONY: docker-build-local docker-buildx

# Single-arch build for local testing (no push). Tags :<version> and :latest.
docker-build-local:
	docker build \
	  -t $(DOCKER_REPO):$(DOCKER_TAG) \
	  -t $(DOCKER_REPO):latest \
	  .

# Multi-arch build + push to Docker Hub. One-time setup:
#   docker login
#   docker buildx create --use --name hashgg-builder
docker-buildx:
	docker buildx build \
	  --platform linux/amd64,linux/arm64 \
	  -t $(DOCKER_REPO):$(DOCKER_TAG) \
	  -t $(DOCKER_REPO):latest \
	  --push \
	  .
